server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.os.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/DeptMapper.xml
spring:
  application:
    name: zjtlapp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 200420
    #将Eureka的客户端和服务端进行绑定
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  #显示IP地址
  instance:
    instance-id: zjtl8001
    prefer-ip-address: true
info:
  app.name: myspringcloudproject
  company.name: www.baidupalus.com
  build.artifactid: @project.artifactId@
  build.version: @project.version@




